"team_name": "JIM" # Your team name
"eval_method": ["reward"] # mcqa, reward, rag, quantiz
"task_type": "causal_lm" # causal_lm, seq2seq
"policy_model_path": "./checkpoints/model_output_dpo_nectar/" # Your path to the final checkpoint in HF: mya_coder/policy_jim_model (https://huggingface.co/mya-coder/policy-jim-model)
"reference_model_path": "./checkpoints/model_SFT_final/" # The repo id of your pretrained reference model in HF: mya_coder/reference_jim_model (https://huggingface.co/mya-coder/reference-jim-model)
"quantized_policy_model_path": "./checkpoints/best_model_quantized/" # Your path to the final quantized checkpoint
"rag_policy_model_path": "./checkpoints/best_model_rag/" # Your path to the final RAG checkpoint
"test_data_path": "./data/test/nectar_test_dataset_3000.jsonl" # Your path to the test data
"dpo_model_args": null # Put any model arguments required to load your DPO model below
"rag_model_args": # Put any model arguments required to load your rag model below
  "encoder_model_path": "facebook/bart-large"
  "retriever_model_path": "./checkpoints/rag_retriever"
  "document_dir": "./data/documents"
"quantized_model_args": null # Put any model arguments required to load your quantized model below
